### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [weiserhei/threejs-fps#1]
Hello, under what license is this project released under ? Thank-you.

**Comment by weiserhei** [comment]
Hi,
I have not thought about this, but I cant really put it into something. There are bits and pieces from around the web (3D-Models, Code Snippets, and everything I got my Hand on) which helped me build this prototype. As far as I can say about this repository/my work, do whatever you want with it.

**Comment by suprafun** [comment]
Thank-you.
